name: linting and security check

on: [push]

jobs:
  check:
    name: linting and security check
    runs-on: ubuntu-latest

    # env:
    #     TFSEC_VERSION: 1.28.11
    #     TFLINT_VERSION: 0.53.0
    #     TF_VERSION: 1.9.8

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Install tfsec
        env:
          TFSEC_VERSION: v1.28.1  # Replace with the desired version
        run: |
          wget -q -O tfsec https://github.com/aquasecurity/tfsec/releases/download/${TFSEC_VERSION}/tfsec-linux-amd64
          chmod +x tfsec
          sudo mv tfsec /usr/local/bin/

  init:
    name: init
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: terraform init
        run: |
          terraform init
      
      - name: terraform plan
        run: |
          terraform plan
      
